name: recipes
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  dotenv: ^4.0.1
  equatable: ^2.0.3
  mongo_dart: ^0.7.4+1
  sealed_unions: ^3.0.3+1
  shelf: ^1.3.0
  shelf_plus: ^1.2.3
  shelf_router: ^1.1.2
  test: ^1.21.1
